general {
    lock_cmd = pidof hyprlock || hyprlock       # evita multiplas instancias
    before_sleep_cmd = loginctl lock-session     # trava antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on    # liga a tela ao acordar
}

# Trava a sessao apos 5 min de inatividade
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Desliga a tela 30s depois de travar
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
